- AUTHORS.rst
- invenio_assets/bower.py
- invenio_assets/ext.py
- invenio_assets/filters.py
- setup.py
- tests/test_invenio_assets.py
* Adds setuptools 18.4+ compatibility for test command.
> installation: setuptools compatiblity

- .travis.yml
- invenio_assets/ext.py
- setup.py
- tests/conftest.py
- tests/test_invenio_assets.py
- tests/test_invenio_assets_cli.py
- tests/test_invenio_assets_filters.py
* Increases the code coverage of the tests. (closes #5)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
> tests: increase of test coverage

- INSTALL.rst
- invenio_assets/ext.py
- tests/test_invenio_assets.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> ext: fix missing build.js

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_assets/version.py
> Invenio-Assets v1.0.0a2

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_assets/version.py
> Invenio-Assets v1.0.0a3

- invenio_assets/cli.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> cli: removal of letters from npm package version

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_assets/version.py
> release: v1.0.0a4

- invenio_assets/version.py
> version: post-release bump

- AUTHORS.rst
- docs/conf.py
- invenio_assets/__init__.py
- invenio_assets/cli.py
- invenio_assets/ext.py
- run-tests.sh
- setup.cfg
- setup.py
- tests/conftest.py
- tests/test_invenio_assets.py
- tests/test_invenio_assets_filters.py
> global: fix CLI for Flask 0.11

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_assets/version.py
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
> release: v1.0.0a5

- .travis.yml
- CHANGES.rst
- INSTALL.rst
- RELEASE-NOTES.rst
- docs/api.rst
- docs/conf.py
- invenio_assets/__init__.py
- invenio_assets/cli.py
- invenio_assets/ext.py
- invenio_assets/filters.py
- invenio_assets/npm.py
- invenio_assets/version.py
- setup.py
- tests/conftest.py
- tests/test_invenio_assets.py
- tests/test_invenio_assets_filters.py
> global: docs, PyPy and Flask>=0.11

- .travis.yml
- docs/api.rst
- docs/conf.py
- docs/index.rst
- invenio_assets/__init__.py
- invenio_assets/cli.py
- invenio_assets/ext.py
- invenio_assets/filters.py
- invenio_assets/proxies.py
- setup.py
- tests/conftest.py
- tests/test_npm.py
* Renames `proxy.py` to `proxies.py` to unify naming with other Invenio
packages.
* Renames `entrypoint` argument to `entry_point_group` to unify naming
with other Invenio extensions.
* Adds documentation for function and method arguments.  (closes #27)
> global: package unification

- .kwalitee.yml
- AUTHORS.rst
- MANIFEST.in
* Fixed my own git name in AUTHORS.rst.
* Added .kwalitee.yml with my alternative git name (present in a commit
originated from GitHub).
Signed-off-by: Ivan Masár <helix84@centrum.sk>
> docs: fix author name

- AUTHORS.rst
- docs/conf.py
- invenio_assets/__init__.py
Signed-off-by: Alizee Pace <alizee.pace@gmail.com>
(closes #34)
> docs: replacement of HTTP with HTTPS

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_assets/version.py
> release: v1.0.0a2

- invenio_assets/collect.py
- invenio_assets/ext.py
- tests/conftest.py
- tests/test_invenio_assets_cli.py
- tests/test_invenio_assets_filters.py
* Fixes issue with modified files not being copied to static root on
reruns of collect CLI command when the application static folder was
also the Flask-Collect's static root.
* Refactors some test cases.
> collect: modified files copy fix

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_assets/version.py
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>
> release: v1.0.0b3

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_assets/version.py
> release: v1.0.0b4

- invenio_assets/filters.py
- tests/test_invenio_assets_filters.py
@andrewm89 can you please test this improved and (hopefully) more reliable language code matching?
> filters: language code matching

- .editorconfig
- .gitignore
- .travis.yml
- CHANGES.rst
- CONTRIBUTING.rst
- INSTALL.rst
- MANIFEST.in
- README.rst
- docs/Makefile
- docs/conf.py
- docs/configuration.rst
- docs/index.rst
- docs/make.bat
- docs/usage.rst
- run-tests.sh
- setup.cfg
- setup.py
- tests/conftest.py
* FIX Adds changes according to release preparation checklist.
Signed-off-by: Rémi Ducceschi <remi.ducceschi@gmail.com>
> global: release checklist

- docs/configuration.rst
- invenio_assets/__init__.py
* Adds documentation for custom RequireJS usage.
* Links config variables to Flask documentation.
(closes #28)
Signed-off-by: Rémi Ducceschi <remi.ducceschi@gmail.com>
> docs: update structure

- .travis.yml
- INSTALL.rst
- README.rst
- docs/configuration.rst
- invenio_assets/__init__.py
- invenio_assets/filters.py
- tests/test_invenio_assets_filters.py
* NEW Adds support for clean-css v.4 via the filter `CleanCSS4Filter`
(closes #59)
Signed-off-by: Rémi Ducceschi <remi.ducceschi@gmail.com>
> filters: support for clean-css v.4

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_assets/version.py
> release: v1.0.0b5

- README.rst
> docs: experimental warning removal

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_assets/version.py
> release: v1.0.0b6

- .travis.yml
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> travis: update nodejs to v6 LTS

- CHANGES.rst
- invenio_assets/version.py
> release: v1.1.0

- invenio_assets/assets/build/webpack.config.js
- invenio_assets/assets/package.json
* Fixes JavaScript minification when running in "production"
mode. (closes #90)
Co-Authored-By: Rokas Maciulaitis <rokas.maciulaitis@cern.ch>
> webpack: add JS minification

- invenio_assets/__init__.py
- setup.py
> global: pin pytest version and fix code checks

- invenio_assets/__init__.py
* Fixes indentation caused by Example being considered a section
> docs: fix indentation

- invenio_assets/assets/build/webpack.config.js
> webpack: turns off webpack warnings

- CHANGES.rst
- invenio_assets/version.py
> release: v1.1.3

- CHANGES.rst
- invenio_assets/assets/build/webpack.config.js
- invenio_assets/assets/package.json
- invenio_assets/version.py
- tests/test_webpack.py
> Semantic-UI support for webpack

- pytest.ini
- run-tests.sh
Part of https://github.com/inveniosoftware/opensource/issues/65
> Fixed Isort 

- invenio_assets/assets/build/webpack.config.js
- create directories for webpack aliases if they do not exist
- formatted prettierjs
> webpack: create directories if they do not exist

- invenio_assets/assets/package.json
Fixes #144
:heart: Thank you for your contribution!
The `node-sass` dependency is deprecated. Changed to `sass` (see #144)
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
Most of the above are not applicable to this PR. It does change one of the dependencies, but this appears to be the community recommended successor to `node-sass`.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-serv …
> Replace `node-sass` dependency with `sass`

- invenio_assets/assets/build/webpack.config.js
- invenio_assets/assets/package.json
:heart: Thank you for your contribution!
Partially Closes [#421](https://github.com/zenodo/rdm-project/issues/421)
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that …
> editor: added plugin for tinymce css files

- .github/workflows/tests.yml
- invenio_assets/assets/package.json
- setup.cfg
> setup: bump pywebpack

- .github/workflows/pypi-publish.yml
- .github/workflows/tests.yml
- CHANGES.rst
- invenio_assets/__init__.py
- setup.cfg
- setup: pin dependencies
- setup: change to reusable workflows
- release: v3.0.4
> pin dependencies

- CHANGES.rst
- invenio_assets/__init__.py
- setup.cfg
- setup: bump invenio dependencies
- release: v4.0.0
NOTE: running it locally with FLASK_DEBUG=1 produces two errors. is that intended, a problem or ignorable?
> bump major
